Repository ros-infrastructure/ros_buildfarm, pull requests merged in 2018-03, with the labels that each got.

#515 git clone with --recurse-submodules
  ros_buildfarm/templates/devel/devel_script_clone.sh.em
  ros_buildfarm/templates/snippet/scm_git.xml.em
Labels: enhancement

#521 Generate YAML of build information
  ros_buildfarm/status_page.py
Labels: enhancement

#531 Fix typo
  ros_buildfarm/templates/devel/devel_job.xml.em
Labels: bug

#530 Fix duplicate apt repos
  ros_buildfarm/templates/snippet/add_additional_repositories.Dockerfile.em
Labels: enhancement, in review

#533 do not generate a blocked-releases job for the first distro
  scripts/generate_all_jobs.py
Labels: in review

#534 remove using the test_depend from binary jobs
  ros_buildfarm/release_job.py
Labels: in review
