Repository ros-infrastructure/ros_buildfarm, pull requests merged in 2018-07, with the labels that each got.

#561 Allow searching by email on status pages
  ros_buildfarm/templates/status/js/setup.js
Labels: enhancement

#562 use version number on -modules dependency
  ros_buildfarm/__init__.py
  setup.py
  stdeb.cfg
Labels: bug

#564 update dpkg to fix installation problems with catkin-pkg
  .travis.yml
Labels: bug, in review

#566 install updated version of dpkg on Trusty
  ros_buildfarm/templates/snippet/add_distribution_repositories.Dockerfile.em
Labels: in review
