Repository ros-infrastructure/ros_buildfarm, pull requests merged in 2018-04, with the labels that each got.

#536 update changelog for upcoming major version
  CHANGELOG.rst
Labels: in review

#537 add missing import from future for python2 compatibility
  scripts/doc/create_doc_task_generator.py
  scripts/doc/extract_metadata.py
  scripts/doc/generate_doc_independent_job.py
  scripts/doc/generate_doc_maintenance_jobs.py
  scripts/doc/generate_doc_metadata_job.py
  scripts/release/check_sync_criteria.py
Labels: bug

#532 Use egrep to find repository components in arbitrary positions.
  ros_buildfarm/templates/snippet/add_additional_repositories.Dockerfile.em
Labels: enhancement
