Repository ros-infrastructure/ros_buildfarm, pull requests merged in 2019-08, with the labels that each got.

#659 install colcon-metadata to get metadata from colcon.pkg files
  scripts/ci/build_task_generator.py
  scripts/ci/create_workspace_task_generator.py
  scripts/devel/create_devel_task_generator.py
Labels: bug

#662 fix checking evaluate conditions in CI jobs
  scripts/ci/generate_install_lists.py
Labels: bug

#663 Add --dry-run option to generate_ci_job
  scripts/ci/generate_ci_job.py
Labels: enhancement, in review

#664 Add CI config 'jenkins_job_upstream_trigger'
  doc/configuration_options.rst
  ros_buildfarm/ci_job.py
  ros_buildfarm/config/ci_build_file.py
  ros_buildfarm/templates/ci/ci_job.xml.em
Labels: enhancement, in review

#661 add option to configure CI jobs using repository names from rosdistro
  doc/configuration_options.rst
  ros_buildfarm/__init__.py
  ros_buildfarm/argument.py
  ros_buildfarm/ci_job.py
  ros_buildfarm/config/ci_build_file.py
  ros_buildfarm/templates/ci/ci_create_tasks.Dockerfile.em
  ros_buildfarm/templates/ci/ci_job.xml.em
  ros_buildfarm/templates/ci/create_workspace.Dockerfile.em
  scripts/ci/create_workspace.py
  scripts/ci/create_workspace_task_generator.py
  scripts/ci/run_ci_job.py
  setup.py
Labels: enhancement, in review

#667 make order of build env vars deterministic
  ros_buildfarm/ci_job.py
  ros_buildfarm/devel_job.py
  ros_buildfarm/release_job.py
Labels: bug, in review

#668 evaluate dependency conditions in doc jobs
  scripts/doc/create_doc_task_generator.py
Labels: bug, in review

#635 Embed repository GPG key.
  .travis.yml
Labels: in review

#670 Support any number of layered workspaces
  .travis.yml
  ros_buildfarm/ci_job.py
  ros_buildfarm/templates/ci/ci_job.xml.em
  ros_buildfarm/templates/devel/devel_create_tasks.Dockerfile.em
  ros_buildfarm/templates/devel/devel_task.Dockerfile.em
  scripts/ci/build_task_generator.py
  scripts/devel/create_devel_task_generator.py
  scripts/prerelease/generate_prerelease_script.py
Labels: enhancement, in review
