Repository ros-infrastructure/ros_buildfarm, pull requests merged in 2019-12, with the labels that each got.

#690 inject downstream job dependencies for ros_workspace
  ros_buildfarm/release_job.py
Labels: bug, in review

#684 add rosdep_update_options
  ros_buildfarm/argument.py
  ros_buildfarm/templates/devel/devel_create_tasks.Dockerfile.em
  ros_buildfarm/templates/doc/doc_create_task.Dockerfile.em
  scripts/devel/run_devel_job.py
  scripts/doc/run_doc_job.py
  scripts/prerelease/generate_prerelease_script.py
Labels: enhancement

#689 Add post test plots for performance test
  doc/configuration_options.rst
  ros_buildfarm/ci_job.py
  ros_buildfarm/config/ci_build_file.py
  ros_buildfarm/config/plot_config.py
  ros_buildfarm/templates/ci/ci_job.xml.em
  ros_buildfarm/templates/snippet/plot_plugin.xml.em
Labels: enhancement

#691 Always update apt cache for CI dependency enumeration
  ros_buildfarm/templates/ci/create_workspace.Dockerfile.em
Labels: bug

#681 Implement the abichecker run on devel builds
  doc/configuration_options.rst
  ros_buildfarm/argument.py
  ros_buildfarm/common.py
  ros_buildfarm/config/source_build_file.py
  ros_buildfarm/devel_job.py
  ros_buildfarm/templates/devel/devel_create_tasks.Dockerfile.em
  ros_buildfarm/templates/devel/devel_job.xml.em
  ros_buildfarm/templates/devel/devel_task.Dockerfile.em
  ros_buildfarm/templates/snippet/publisher_abi_report.xml.em
  ros_buildfarm/templates/snippet/publisher_parser_rules/generic_unstable.parser
  ros_buildfarm/templates/snippet/publisher_parser_unstable.xml.em
  scripts/ci/build_task_generator.py
  scripts/devel/build_and_install.py
  scripts/devel/create_devel_task_generator.py
  scripts/devel/generate_devel_script.py
  scripts/devel/run_devel_job.py
Labels: enhancement, in review

#698 Update plugin versions.
  ros_buildfarm/templates/dashboard_view_all_jobs.xml.em
  ros_buildfarm/templates/dashboard_view_devel_jobs.xml.em
  ros_buildfarm/templates/snippet/builder_system-groovy.xml.em
  ros_buildfarm/templates/snippet/copy_artifacts.xml.em
  ros_buildfarm/templates/snippet/property_github-project.xml.em
  ros_buildfarm/templates/snippet/publisher_abi_report.xml.em
  ros_buildfarm/templates/snippet/publisher_extended-email.xml.em
  ros_buildfarm/templates/snippet/publisher_groovy-postbuild.xml.em
  ros_buildfarm/templates/snippet/publisher_mailer.xml.em
  ros_buildfarm/templates/snippet/publisher_publish-over-git.xml.em
  ros_buildfarm/templates/snippet/scm_git.xml.em
Labels: in review
