Repository ros-infrastructure/ros_buildfarm, pull requests merged in 2019-07, with the labels that each got.

#642 Fix CI build detection of non-ROS packages
  scripts/ci/generate_install_lists.py
Labels: bug, in review

#644 Fix a regression in CI builds with no package selection args
  scripts/ci/generate_install_lists.py
Labels: bug, in review

#645 Don't override MAKEFLAGS blindly
  scripts/devel/build_and_install.py
  scripts/devel/build_and_test.py
  scripts/doc/build_doc.py
Labels: enhancement

#646 set git user email and name for 'git merge' to work
  ros_buildfarm/templates/ci/create_workspace.Dockerfile.em
Labels: bug, in review

#647 allow 'vcs export --exact' to fail when merging a branch
  ros_buildfarm/vcs.py
  scripts/ci/create_workspace.py
Labels: bug, in review

#648 Manually inspect colcon index to find CI underlay packages
  scripts/ci/generate_install_lists.py
Labels: bug, in review

#650 Fix extra build tool arguments when testing with colcon
  scripts/devel/build_and_test.py
Labels: bug

#649 add link to ci_jobs.rst
  doc/index.rst
Labels: enhancement

#653 Fix CI job generation when called from generate_all_jobs
  scripts/generate_all_jobs.py
Labels: bug

#655 Prevent colcon from crawling the catkin results
  ros_buildfarm/workspace.py
Labels: bug

#656 Use --no-log-init to prevent Docker build from hanging
  ros_buildfarm/templates/ci/ci_create_reconfigure_task.Dockerfile.em
  ros_buildfarm/templates/ci/ci_create_tasks.Dockerfile.em
  ros_buildfarm/templates/ci/create_workspace.Dockerfile.em
  ros_buildfarm/templates/devel/devel_create_reconfigure_task.Dockerfile.em
  ros_buildfarm/templates/devel/devel_create_tasks.Dockerfile.em
  ros_buildfarm/templates/devel/devel_task.Dockerfile.em
  ros_buildfarm/templates/doc/doc_create_reconfigure_task.Dockerfile.em
  ros_buildfarm/templates/doc/doc_create_task.Dockerfile.em
  ros_buildfarm/templates/doc/doc_independent_task.Dockerfile.em
  ros_buildfarm/templates/doc/doc_metadata_task.Dockerfile.em
  ros_buildfarm/templates/doc/doc_task.Dockerfile.em
  ros_buildfarm/templates/misc/rosdistro_cache_task.Dockerfile.em
  ros_buildfarm/templates/release/binarydeb_create_task.Dockerfile.em
  ros_buildfarm/templates/release/binarydeb_task.Dockerfile.em
  ros_buildfarm/templates/release/release_check_sync_criteria_task.Dockerfile.em
  ros_buildfarm/templates/release/release_create_reconfigure_task.Dockerfile.em
  ros_buildfarm/templates/release/release_create_trigger_task.Dockerfile.em
  ros_buildfarm/templates/release/sourcedeb_task.Dockerfile.em
  ros_buildfarm/templates/status/blocked_releases_page_task.Dockerfile.em
  ros_buildfarm/templates/status/release_compare_page_task.Dockerfile.em
  ros_buildfarm/templates/status/release_status_page_task.Dockerfile.em
Labels: enhancement
