Repository ros-infrastructure/ros_buildfarm, pull requests merged in 2019-06, with the labels that each got.

#634 set ROS_PYTHON_VERSION when evaluating conditions
  scripts/devel/create_devel_task_generator.py
Labels: bug, in review

#636 fix logic to ignore packages in CI builds
  ros_buildfarm/templates/ci/create_workspace.Dockerfile.em
  scripts/ci/create_workspace.py
  scripts/ci/generate_install_lists.py
Labels: bug, in review

#639 add changelog for upcoming major version
  CHANGELOG.rst
Labels: in review

#641 Update GPG key and move to supported platform for CI builds
  .travis.yml
Labels: bug
