Repository ros-infrastructure/ros_buildfarm, pull requests merged in 2020-03, with the labels that each got.

#745 Disable weak dependencies on RHEL 7 builds
  ros_buildfarm/templates/release/rpm/mock_config.cfg.em
Labels: enhancement

#740 Added description field for the plot plugin
  doc/configuration_options.rst
  ros_buildfarm/config/plot_config.py
  ros_buildfarm/templates/snippet/plot_plugin.xml.em
Labels: enhancement

#748 Reduce uniqueness of docker images to prevent continuous aggregation
  ros_buildfarm/templates/ci/ci_job.xml.em
Labels: enhancement

#750 Include filtered packages in status pages
  ros_buildfarm/status_page_input.py
  ros_buildfarm/templates/status/css/status_page.css
Labels: enhancement

#756 Pass env vars from build config to RPM build
  ros_buildfarm/templates/release/rpm/mock_config.cfg.em
Labels: bug, in review

#757 Improve performance of RPM repo sync operations
  scripts/release/rpm/import_package.py
Labels: enhancement, in review

#759 Fix source RPM job regression
  scripts/release/rpm/run_sourcepkg_job.py
Labels: bug, in review

#760 Change --env-vars to parse as a dict
  ros_buildfarm/argument.py
  ros_buildfarm/templates/ci/ci_create_tasks.Dockerfile.em
  ros_buildfarm/templates/devel/devel_create_tasks.Dockerfile.em
  ros_buildfarm/templates/release/rpm/mock_config.cfg.em
  scripts/ci/build_task_generator.py
  scripts/ci/create_workspace_task_generator.py
  scripts/devel/create_devel_task_generator.py
  scripts/release/create_binarydeb_task_generator.py
  scripts/release/rpm/run_binarypkg_job.py
  scripts/release/rpm/run_sourcepkg_job.py
  scripts/release/run_binarydeb_job.py
Labels: enhancement, in review

#763 Fix a regression in RPM jobs
  ros_buildfarm/templates/release/rpm/mock_config.cfg.em
  scripts/release/rpm/run_sourcepkg_job.py
Labels: bug, in review

#762 Drop manifest conditional evaluation from abi checker
  ros_buildfarm/common.py
  scripts/devel/build_and_install.py
Labels: enhancement, in review

#761 Unify approach to computing package conditional context
  ros_buildfarm/common.py
  scripts/doc/create_doc_task_generator.py
Labels: enhancement, in review

#758 Process conditional dependencies in release jobs
  ros_buildfarm/common.py
  ros_buildfarm/release_job.py
Labels: enhancement, in review

#765 fix merging hard coded args with configuration provided args
  ros_buildfarm/workspace.py
Labels: bug

#767 Resolve group membership and use in topological ordering
  ros_buildfarm/common.py
  ros_buildfarm/release_job.py
Labels: in review

#768 Refactor pulp workflows into a common file
  ros_buildfarm/pulp.py
  scripts/release/rpm/import_package.py
  scripts/release/rpm/list_packages.py
  scripts/release/rpm/upload_package.py
Labels: enhancement, in review

#770 Create a standalone script for performing pulp repo syncs
  ros_buildfarm/pulp.py
  ros_buildfarm/templates/release/rpm/import_package_job.xml.em
  ros_buildfarm/templates/release/rpm/sync_packages_to_testing_job.xml.em
  scripts/release/rpm/import_package.py
  scripts/release/rpm/list_packages.py
  scripts/release/rpm/sync_repo.py
Labels: enhancement, in review

#769 Use directory arguments on deb job scripts for decoupling
  ros_buildfarm/templates/release/deb/binarypkg_job.xml.em
  ros_buildfarm/templates/release/deb/sourcepkg_task.Dockerfile.em
  scripts/release/run_sourcedeb_job.py
Labels: enhancement, in review

#771 Add sync-to-main job for RPM repos
  ros_buildfarm/release_job.py
  ros_buildfarm/templates/release/rpm/sync_packages_to_main_job.xml.em
Labels: enhancement, in review

#772 use Python 3 / pip3 to install Python dependencies in doc jobs
  ros_buildfarm/templates/doc/doc_independent_task.Dockerfile.em
Labels: bug

#775 Don't tell apt which versions of debian packages to install
  ros_buildfarm/templates/snippet/install_dependencies_from_file.Dockerfile.em
  scripts/ci/generate_install_lists.py
Labels: bug

#773 Sort CI job plot groups in Jenkins job XML
  ros_buildfarm/templates/snippet/plot_plugin.xml.em
Labels: in review

#774 Support RPM repo sync with multiple destinations
  ros_buildfarm/templates/release/rpm/sync_packages_to_main_job.xml.em
  ros_buildfarm/templates/release/rpm/sync_packages_to_testing_job.xml.em
  scripts/release/rpm/sync_repo.py
Labels: enhancement, in review

#776 Address Travis configuration warnings and lint
  .travis.yml
Labels: in review

#778 Fine-tune the behavior of the rpm/sync_repo.py script
  ros_buildfarm/pulp.py
  ros_buildfarm/templates/release/rpm/sync_packages_to_main_job.xml.em
  ros_buildfarm/templates/release/rpm/sync_packages_to_testing_job.xml.em
  scripts/release/rpm/sync_repo.py
Labels: enhancement, in review

#777 Assume ros_buildfarm RPM repos will sign metadata
  ros_buildfarm/templates/release/rpm/mock_config.cfg.em
Labels: in review

#779 Add RPM import_upstream job
  ros_buildfarm/pulp.py
  ros_buildfarm/templates/release/rpm/import_upstream_job.xml.em
  scripts/release/generate_release_maintenance_jobs.py
  scripts/release/rpm/mirror_repo.py
Labels: enhancement, in review

#780 Never skip ros_buildfarm RPM repositories
  ros_buildfarm/templates/release/rpm/mock_config.cfg.em
Labels: bug, in review

#781 Update repository status page to support RPM
  ros_buildfarm/argument.py
  ros_buildfarm/status_page.py
  ros_buildfarm/templates/status/repos_status_page_job.xml.em
  scripts/status/build_repos_status_page.py
  scripts/status/generate_repos_status_page_job.py
Labels: enhancement, in review

#782 Add '$distname' resolution to RPM URLs
  ros_buildfarm/rpm_repo.py
Labels: enhancement, in review

#783 Refactor get_package_repo_data out of common
  ros_buildfarm/common.py
  ros_buildfarm/package_repo.py
  ros_buildfarm/status_page.py
  ros_buildfarm/trigger_job.py
Labels: enhancement, in review
