Repository ros-infrastructure/ros_buildfarm, pull requests merged in 2020-05, with the labels that each got.

#803 clarify docs for custom distribution files and tags
  doc/custom_rosdistro.rst
Labels: enhancement

#809 Support latest flake8 release
  ros_buildfarm/binarydeb_job.py
  ros_buildfarm/debian_repo.py
  test/test_flake8.py
Labels: bug, in review

#804 Disable mock bootstrapping in RPM builds
  ros_buildfarm/templates/release/rpm/mock_config.cfg.em
Labels: bug, in review

#805 Enable mock postinstall feature in RPM builds
  ros_buildfarm/binaryrpm_job.py
Labels: enhancement, in review

#806 Enable RPM debug packages
  ros_buildfarm/templates/release/rpm/binarypkg_job.xml.em
  ros_buildfarm/templates/snippet/builder_parameterized-trigger.xml.em
Labels: enhancement, in review

#807 Support multiple iter(...) invocations on pulp iterator
  ros_buildfarm/pulp.py
Labels: bug, in review

#808 Add workaround and WARNING for pulp issue #6811
  ros_buildfarm/pulp.py
Labels: bug, in review
