Repository ros-infrastructure/ros_buildfarm, pull requests merged in 2020-08, with the labels that each got.

#828 use distinct xunit pattern for ROS 2
  ros_buildfarm/ci_job.py
  ros_buildfarm/common.py
  ros_buildfarm/devel_job.py
  ros_buildfarm/templates/snippet/publisher_xunit.xml.em
Labels: bug

#833 Add --dry-run argument to generate_devel_job.py
  scripts/devel/generate_devel_job.py
Labels: enhancement, in review

#838 Fix the indentation for the warnings job snippet
  ros_buildfarm/templates/snippet/publisher_warnings.xml.em
Labels: bug, in review

#837 Fix the Jenkins job authorization snippet order
  ros_buildfarm/templates/ci/ci_job.xml.em
Labels: bug, in review

#834 Support custom !include directive in config files
  doc/index.rst
  ros_buildfarm/config/__init__.py
Labels: enhancement, in review
