Repository ros-infrastructure/ros_buildfarm, pull requests merged in 2020-04, with the labels that each got.

#785 Introduce a PlatformPackageDescriptor object
  ros_buildfarm/common.py
  ros_buildfarm/debian_repo.py
  ros_buildfarm/rpm_repo.py
  ros_buildfarm/status_page.py
  ros_buildfarm/templates/status/release_status_page.html.em
  ros_buildfarm/trigger_job.py
Labels: enhancement, in review

#787 Don't show subpackage source packages as missing
  ros_buildfarm/common.py
  ros_buildfarm/debian_repo.py
  ros_buildfarm/rpm_repo.py
  ros_buildfarm/status_page.py
Labels: enhancement, in review

#788 Don't consider source package name if not provided
  ros_buildfarm/status_page.py
Labels: bug, in review

#789 Pin pyparsing 2.4.7 for Python 3.4 and 2.7 Travis CI jobs.
  .travis.yml
Labels: bug

#784 Add support to archive arbitrary artifacts in CI jobs.
  doc/configuration_options.rst
  ros_buildfarm/ci_job.py
  ros_buildfarm/config/ci_build_file.py
  ros_buildfarm/templates/ci/ci_job.xml.em
Labels: enhancement, in review

#794 Allow file:// URLs to .repos files in CI jobs
  ros_buildfarm/templates/ci/ci_create_tasks.Dockerfile.em
  ros_buildfarm/templates/ci/create_workspace.Dockerfile.em
  scripts/ci/create_workspace_task_generator.py
  scripts/ci/run_ci_job.py
Labels: enhancement, in review

#792 Support --build-tool-args in generate_ci_script.py
  scripts/ci/generate_ci_script.py
Labels: enhancement, in review

#791 Enable package selection at build time in CI
  scripts/ci/build_task_generator.py
Labels: enhancement, in review

#795 readd flake8_docstrings, add flake8_class_newline
  .travis.yml
  ros_buildfarm/argument.py
  ros_buildfarm/common.py
  ros_buildfarm/config/ci_build_file.py
  ros_buildfarm/config/plot_config.py
  ros_buildfarm/pulp.py
  setup.py
Labels: in review

#793 Add build_tool_test_args parameter to CI jobs
  doc/configuration_options.rst
  ros_buildfarm/argument.py
  ros_buildfarm/ci_job.py
  ros_buildfarm/config/ci_build_file.py
  ros_buildfarm/templates/ci/ci_create_tasks.Dockerfile.em
  ros_buildfarm/templates/ci/ci_job.xml.em
  ros_buildfarm/templates/devel/devel_task.Dockerfile.em
  scripts/ci/build_task_generator.py
  scripts/ci/generate_ci_script.py
  scripts/ci/run_ci_job.py
  scripts/devel/build_and_test.py
Labels: enhancement, in review

#797 fix missing static analysis issues column
  ros_buildfarm/templates/dashboard_view_devel_jobs.xml.em
Labels: bug

#798 only show failed test numbers in chart
  ros_buildfarm/templates/dashboard_view_devel_jobs.xml.em
Labels: enhancement
