Repository ros-infrastructure/ros_buildfarm, pull requests merged in 2020-07, with the labels that each got.

#818 Changes for compatibility with the latest Pulp release
  ros_buildfarm/pulp.py
Labels: bug, in review

#819 Fix repository GPG keys for RPM
  ros_buildfarm/templates/release/rpm/binarypkg_task.Dockerfile.em
  ros_buildfarm/templates/release/rpm/mock_config.cfg.em
  ros_buildfarm/templates/release/rpm/sourcepkg_task.Dockerfile.em
Labels: bug, in review

#822 fix failing CI
  .travis.yml
Labels: bug

#821 quote test args containing spaces
  ros_buildfarm/templates/devel/devel_task.Dockerfile.em
  ros_buildfarm/workspace.py
Labels: bug

#823 Ensure RPM mock macros start with % character
  ros_buildfarm/templates/release/rpm/mock_config.cfg.em
Labels: bug, in review

#825 Add Fedora to repos status page platform list
  scripts/status/generate_repos_status_page_job.py
Labels: enhancement, in review
