Repository ros-infrastructure/ros_buildfarm, pull requests merged in 2020-01, with the labels that each got.

#696 create '/$HOME/.ccache' as a user before mounting it
  ros_buildfarm/templates/devel/devel_job.xml.em
  ros_buildfarm/templates/release/binarydeb_job.xml.em
Labels: bug

#697 Added to plot plugin y max and min values
  doc/configuration_options.rst
  ros_buildfarm/config/plot_config.py
  ros_buildfarm/templates/snippet/plot_plugin.xml.em
Labels: enhancement

#694 Skip unreleased packages from ABI checking
  ros_buildfarm/templates/devel/devel_task.Dockerfile.em
  scripts/devel/build_and_install.py
Labels: bug

#704 Add short name mapping entries for RPM distros
  ros_buildfarm/common.py
Labels: enhancement

#624 GPU support for build files
  doc/configuration_options.rst
  ros_buildfarm/argument.py
  ros_buildfarm/config/source_build_file.py
  ros_buildfarm/devel_job.py
  ros_buildfarm/templates/devel/devel_create_tasks.Dockerfile.em
  ros_buildfarm/templates/devel/devel_job.xml.em
  ros_buildfarm/templates/devel/devel_task.Dockerfile.em
  ros_buildfarm/templates/snippet/setup_nvidia_docker2.Dockerfile.em
  scripts/ci/build_task_generator.py
  scripts/devel/build_and_test.py
  scripts/devel/create_devel_task_generator.py
  scripts/devel/generate_devel_script.py
  scripts/devel/run_devel_job.py
Labels: enhancement, in review

#705 Use platform-neutral term 'pkg' in place of 'deb' in CLA
  ros_buildfarm/argument.py
  ros_buildfarm/binarydeb_job.py
  ros_buildfarm/templates/release/binarydeb_create_task.Dockerfile.em
  ros_buildfarm/templates/release/binarydeb_job.xml.em
  ros_buildfarm/templates/release/binarydeb_task.Dockerfile.em
  scripts/release/append_build_timestamp.py
  scripts/release/build_binarydeb.py
  scripts/release/create_binarydeb_install_task_generator.py
  scripts/release/create_binarydeb_task_generator.py
  scripts/release/generate_release_script.py
  scripts/release/get_sourcedeb.py
  scripts/release/run_binarydeb_job.py
Labels: enhancement, in review

#703 Add mapping from OS names to packaging formats
  ros_buildfarm/common.py
Labels: enhancement, in review

#708 Use yaml.safe_load
  ros_buildfarm/config/__init__.py
  ros_buildfarm/rosdoc_index.py
  ros_buildfarm/rosdoc_lite.py
  scripts/doc/build_doc.py
  scripts/doc/create_doc_task_generator.py
Labels: enhancement, in review

#707 Refactor and abstract debian repo data caching
  ros_buildfarm/common.py
  ros_buildfarm/debian_repo.py
  ros_buildfarm/http_cache.py
  ros_buildfarm/status_page.py
  ros_buildfarm/templates/release/release_trigger-jobs_job.xml.em
  ros_buildfarm/templates/release/sync_packages_to_testing_job.xml.em
  ros_buildfarm/templates/status/release_status_page_job.xml.em
  ros_buildfarm/templates/status/release_status_page_task.Dockerfile.em
  ros_buildfarm/templates/status/repos_status_page_job.xml.em
  ros_buildfarm/trigger_job.py
  scripts/release/check_sync_criteria.py
  scripts/release/trigger_jobs.py
  scripts/status/build_release_status_page.py
  scripts/status/build_repos_status_page.py
Labels: enhancement, in review

#711 Rename get_debian_package_name function for non-debian use
  ros_buildfarm/binarydeb_job.py
  ros_buildfarm/common.py
  ros_buildfarm/release_job.py
  ros_buildfarm/sourcedeb_job.py
  ros_buildfarm/status_page.py
  ros_buildfarm/status_page_input.py
  ros_buildfarm/trigger_job.py
  scripts/doc/create_doc_task_generator.py
  scripts/release/check_sync_criteria.py
  scripts/release/create_binarydeb_task_generator.py
Labels: enhancement, in review

#712 Use get_short_os_code_name in release status page
  ros_buildfarm/status_page.py
  ros_buildfarm/templates/status/release_status_page.html.em
Labels: enhancement, in review

#713 Add support for RPM repository indexing
  ros_buildfarm/common.py
  ros_buildfarm/rpm_repo.py
  ros_buildfarm/status_page.py
Labels: enhancement, in review

#714 Add support for param files in Jenkins trigger plugin
  ros_buildfarm/templates/release/binarydeb_job.xml.em
  ros_buildfarm/templates/release/sourcedeb_job.xml.em
  ros_buildfarm/templates/snippet/builder_parameterized-trigger.xml.em
Labels: enhancement, in review

#715 Escape $ in repo URLs and strip() the GPG keys
  ros_buildfarm/common.py
Labels: enhancement, in review

#716 Add support for Jenkins credential binding plugin
  ros_buildfarm/templates/snippet/credentials_binding_plugin.xml.em
Labels: enhancement, in review

#720 Add --dry-run option to generate_release_job
  scripts/release/generate_release_job.py
Labels: enhancement, in review

#717 Move debian-specific release templates to a subdirectory
  doc/jobs/release_call_graph.dot
  doc/jobs/release_call_graph.png
  ros_buildfarm/release_job.py
  ros_buildfarm/templates/release/deb/binarypkg_create_task.Dockerfile.em
  ros_buildfarm/templates/release/deb/binarypkg_install_task.Dockerfile.em
  ros_buildfarm/templates/release/deb/binarypkg_job.xml.em
  ros_buildfarm/templates/release/deb/binarypkg_task.Dockerfile.em
  ros_buildfarm/templates/release/deb/import_package_job.xml.em
  ros_buildfarm/templates/release/deb/import_upstream_job.xml.em
  ros_buildfarm/templates/release/deb/sourcepkg_job.xml.em
  ros_buildfarm/templates/release/deb/sourcepkg_task.Dockerfile.em
  ros_buildfarm/templates/release/deb/sync_packages_to_main_job.xml.em
  ros_buildfarm/templates/release/deb/sync_packages_to_testing_job.xml.em
  scripts/release/create_binarydeb_install_task_generator.py
  scripts/release/create_binarydeb_task_generator.py
  scripts/release/generate_release_maintenance_jobs.py
  scripts/release/generate_release_script.py
  scripts/release/run_binarydeb_job.py
  scripts/release/run_sourcedeb_job.py
Labels: enhancement, in review

#719 Front-load manifest parsing and ros_workspace dep injection
  ros_buildfarm/release_job.py
Labels: bug, enhancement, in review

#722 Don't inject ros_workspace dep when there is no ros_workspace
  ros_buildfarm/release_job.py
Labels: bug, in review

#723 use GoogleTest / JUnit test result parser based on file pattern in ROS 2
  ros_buildfarm/ci_job.py
  ros_buildfarm/common.py
  ros_buildfarm/devel_job.py
  ros_buildfarm/templates/ci/ci_job.xml.em
  ros_buildfarm/templates/devel/devel_job.xml.em
  ros_buildfarm/templates/snippet/publisher_xunit.xml.em
Labels: enhancement

#724 limit JUnit type for pytest.xml to Focal, otherwise fall back to GoogleTest
  ros_buildfarm/ci_job.py
  ros_buildfarm/common.py
  ros_buildfarm/devel_job.py
Labels: bug

#726 Add os_name argument to check_sync_criteria
  ros_buildfarm/release_job.py
  ros_buildfarm/templates/release/deb/sync_packages_to_testing_job.xml.em
  ros_buildfarm/templates/release/release_check_sync_criteria_task.Dockerfile.em
  scripts/release/check_sync_criteria.py
  scripts/release/run_check_sync_criteria_job.py
Labels: enhancement, in review

#727 Use debian-similar URL scheme for RPM repo URLs
  ros_buildfarm/common.py
  ros_buildfarm/rpm_repo.py
Labels: enhancement, in review
